#!/bin/sh

# 0. Переменные окружения и чистка Wayland-мусора
export QT_QPA_PLATFORM=xcb
export GDK_BACKEND=x11
export _JAVA_AWT_WM_NONREPARENTING=1
dbus-update-activation-environment --systemd QT_QPA_PLATFORM GDK_BACKEND

# 1. Очистка старых процессов
killall -9 sxhkd eww picom dunst copyq 2>/dev/null

# 2. Горячие клавиши
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &

# 3. Настройка периферии и раскладки
xinput set-prop "ELAN0420:00 04F3:3240 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0420:00 04F3:3240 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "E-Signal USB Gaming Mouse" "libinput Accel Speed" -0.5
xsetroot -cursor_name left_ptr
setxkbmap -layout "us,ru" -option "grp:win_space_toggle" &

# 4. Мониторы (Независимые рабочие столы 1-9 на каждом)
if xrandr | grep -q "HDMI-1 connected"; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 \
           --output HDMI-1 --mode 1920x1080 --right-of eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
    bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
    bspc monitor -f eDP-1
    notify-send "Два монитора" "eDP-1 и HDMI-1 настроены независимо"
else
    xrandr --output eDP-1 --primary --auto --output HDMI-1 --off
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
    notify-send "Один монитор" "Только eDP-1"
fi

# 5. Визуальные сервисы и Буфер обмена
feh --bg-fill /home/roy/Pictures/wallpaper/car.jpg &
picom --config /home/roy/.config/picom/picom.conf --backend glx &
dunst &
copyq &

# 6. Панель EWW
eww daemon &
sleep 0.5
eww open bar &

# 7. Настройки логики окон (в фоне после старта bspwm)
(
    while ! bspc wm -g > /dev/null 2>&1; do sleep 0.1; done

    # APPEARANCE
    bspc config top_padding 40
    bspc config window_gap 7
    bspc config border_width 4
    bspc config split_ratio 0.5
    
    bspc config modifier_mask mod1
    
    # ФОКУС
    bspc config focus_follows_pointer false
    bspc config pointer_follows_focus true

    bspc config pointer_modifier mod1
    bspc config pointer_action1 move
    # ПРАВИЛА
    bspc rule -a AmneziaVPN state=floating
) &
